version: 2.1

jobs:
  push-to-ecr:
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - checkout
      - run: aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $URL
      - run: docker build -t $URL/devops:latest -t $URL/devops:$CIRCLE_BUILD_NUM .
      - run: docker push 935150213092.dkr.ecr.us-east-1.amazonaws.com/devops:latest
      - run: docker push $URL/devops:$CIRCLE_BUILD_NUM
      - run: docker push $URL/devops:latest

workflows:
  version: 2
  aws-cli:
    jobs:
      - push-to-ect
